const fs = require('node:fs')
const path = require('node:path')
const os = require('node:os')
const assert = require('node:assert/strict')
const { _electron } = require('C:/Users/Nick/AppData/Local/npm-cache/_npx/420ff84f11983ee5/node_modules/playwright')

;(async () => {
  const root = path.resolve(__dirname, '../lantern')
  const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'olympus-station-audit-'))
  const projectsRoot = path.join(scratch, 'Projects')
  const project = path.join(projectsRoot, 'Station audit')
  fs.mkdirSync(project, { recursive: true })
  fs.writeFileSync(path.join(project, 'sticker-preview.png'), Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lZkAAAAASUVORK5CYII=', 'base64'))
  fs.writeFileSync(path.join(scratch, 'settings.json'), JSON.stringify({ schemaVersion: 1, projectRoots: [projectsRoot], lastSpace: project.toLowerCase(), permissionMode: 'ask' }))
  const launcher = path.join(scratch, 'launch.cjs')
  fs.writeFileSync(launcher, `const {app}=require('electron');app.setPath('userData',${JSON.stringify(scratch)});app.on('browser-window-created',(_,w)=>{w.show=()=>{};w.setSize(1440,940);w.webContents.setBackgroundThrottling(false)});require(${JSON.stringify(path.join(root, 'dist-electron/main.js'))})`)
  const env = { ...process.env }
  delete env.ELECTRON_RUN_AS_NODE
  const app = await _electron.launch({ executablePath: path.join(root, 'node_modules/electron/dist/electron.exe'), args: [launcher], cwd: root, env })
  try {
    const page = await app.firstWindow()
    page.setDefaultTimeout(30000)
    page.on('pageerror', (error) => console.error('PAGE ERROR', error.message))
    page.on('console', (message) => { if (message.type() === 'error') console.error('CONSOLE ERROR', message.text()) })
    await page.getByRole('button', { name: /^Station(?:\s+\d+)?$/ }).waitFor()
    const projectId = project.toLowerCase()
    const sessionIds = await page.evaluate(async (id) => {
      await window.electronAPI.openSpace(id)
      const workspace = await window.electronAPI.request(id, 'POST', '/session', { title: 'Workspace only' })
      const station = await window.electronAPI.request(id, 'POST', '/session', { title: 'Sticker shop' })
      if (!workspace.ok || !station.ok) throw new Error('Could not create audit sessions')
      localStorage.setItem('olympus.agentWindows', JSON.stringify({ [id]: [workspace.data.id] }))
      localStorage.setItem('olympus.stationSessions', JSON.stringify({ [id]: [station.data.id] }))
      return { workspace: workspace.data.id, station: station.data.id }
    }, projectId)
    await page.reload()
    await page.getByRole('button', { name: /^Station(?:\s+\d+)?$/ }).click()
    const storeLocation = await page.evaluate(async (watchedRoot) => {
      const created = await window.electronAPI.createStore(watchedRoot, 'Separate store')
      const projects = await window.electronAPI.listProjects()
      return { id: created.id, inProjects: projects.some((item) => item.id === created.id) }
    }, projectsRoot)
    assert.equal(storeLocation.inProjects, false)
    assert.equal(storeLocation.id, path.join(scratch, 'Stores', 'Separate store').toLowerCase())
    await page.getByRole('region', { name: 'Store overview' }).waitFor()
    assert.equal(await page.getByRole('region', { name: 'Store overview' }).getByRole('button', { name: 'Daily checks off' }).count(), 1)
    await page.screenshot({ path: path.join(__dirname, 'station-overview-live.png') })
    await page.getByRole('region', { name: 'Store overview' }).getByRole('button', { name: 'Stop', exact: true }).click()
    await page.getByRole('region', { name: 'Store overview' }).getByRole('button', { name: 'Start', exact: true }).waitFor()
    assert.equal((await page.evaluate(() => JSON.parse(localStorage.getItem('olympus.pausedStores') || '[]'))).includes(projectId), true)
    await page.getByRole('region', { name: 'Store overview' }).getByRole('button', { name: 'Start', exact: true }).click()
    await page.getByRole('region', { name: 'Store overview' }).getByRole('button', { name: /Sticker shop/ }).click()
    assert.equal(await page.locator(`article[data-session-id="${sessionIds.station}"]:visible`).count(), 1)
    assert.equal(await page.locator(`article[data-session-id="${sessionIds.workspace}"]:visible`).count(), 0)
    assert.equal(await page.getByRole('navigation', { name: 'Workspace mode' }).count(), 0)
    await page.getByRole('region', { name: 'Live agent activity' }).waitFor()
    await page.getByRole('img', { name: 'sticker-preview.png' }).waitFor()
    await page.getByRole('button', { name: 'New store', exact: true }).click()
    await page.getByLabel('Tell the agent what you want').fill('Make a sticker store for book lovers on Etsy with Canva artwork')
    assert.equal(await page.getByLabel('Store name (optional)').inputValue(), '')
    assert.equal(await page.getByRole('button', { name: 'Build my store' }).isEnabled(), true)
    await page.locator('button[title="Choose a model"]:visible').click()
    const picker = page.getByRole('searchbox', { name: 'Search models' })
    await picker.waitFor()
    assert.equal(await page.getByLabel('Tell the agent what you want').isVisible(), true)
    const box = await picker.boundingBox()
    assert.ok(box && box.x >= 0 && box.x + box.width <= (await page.evaluate(() => window.innerWidth)))
    await page.screenshot({ path: path.join(__dirname, 'station-live.png') })
    console.log(JSON.stringify({ passed: true, checks: ['Stores folder is a sibling of Projects and is absent from Projects', 'Station and Workspace chats are separate', 'Visual store overview and Start/Stop work', 'Station chat shows activity and images', 'Model picker remains visible without submitting the store form'], screenshot: path.join(__dirname, 'station-live.png') }))
  } finally {
    await app.close()
    if (path.dirname(scratch) === os.tmpdir()) fs.rmSync(scratch, { recursive: true, force: true })
  }
})().catch((error) => { console.error(error); process.exitCode = 1 })
