// Flat ESLint config for Olympus.
//
// Design intent: catch real bugs (unreachable code, a misused hook, a floating
// promise, a shadowed import) without becoming a style committee. Olympus has
// no Prettier and no in-house style rules beyond what tsc already enforces, so
// every rule here either catches a defect or documents a deliberate exception.
//
// NOT enabled, and why:
//   - Formatting/indent rules: tsc and the editor handle that; a second
//     opinion here would just produce diff noise on files nobody is editing.
//   - @typescript-eslint/no-explicit-any: set to "warn", not "error". The
//     OpencodeEvent union genuinely models JSON that arrives from a daemon we
//     do not control, and `unknown` + a narrowing cast reads worse than `any`
//     at those boundaries. Fixing them all is a separate refactor.
//   - react-hooks/exhaustive-deps: "warn", because the stream code closes over
//     refs and connection state on purpose; flipping it to error would mean
//     restructuring working code to satisfy a linter.
//
// Run `npm run lint`. Warnings do not fail the script (--max-warnings is not
// set), so the build stays green; zero errors is the bar.

import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'dist-electron/**',
      'release/**',
      'out/**',
      'node_modules/**',
      'coverage/**',
      // Generated by vite-plugin-electron, not source.
      '*.config.js.timestamp*',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node },
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,

      // --- correctness, high value -----------------------------------------
      // Unreachable code after a throw/return is almost always a refactor
      // leftover, and on a first paid release it is a real defect risk.
      'no-unreachable': 'error',
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-self-assign': 'error',
      // A floating promise in the main process means an unhandled rejection at
      // startup, which shows the user a blank window and no explanation.
      'no-async-promise-executor': 'error',
      'no-return-await': 'error',
      'require-atomic-updates': 'warn',

      // --- hygiene ---------------------------------------------------------
      'no-empty': ['error', { allowEmptyCatch: true }],
      'prefer-const': 'error',
      'eqeqeq': ['error', 'smart'],
      'no-var': 'error',

      // --- typescript ------------------------------------------------------
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-non-null-assertion': 'off',
      // tsc --noEmit is the type authority; ESLint has no type information, so
      // the type-aware rules that would duplicate it are left off.
      '@typescript-eslint/ban-ts-comment': 'error',
    },
  },

  {
    // Renderer-only: the preload bridge and the browser context.
    files: ['src/**/*.{ts,tsx}', 'electron/preload.ts'],
    rules: {
      'no-restricted-globals': 'off',
    },
  },

  {
    files: ['tests/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      // Test fixtures deliberately build partial objects and pass through
      // unknown shapes; the casts are the point of the fixture.
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
    },
  },

  {
    files: ['*.config.{js,ts}', 'build/**/*.mjs', 'electron-builder.yml'],
    languageOptions: { globals: { ...globals.node } },
  },
)
