/**
 * How a store gets found by search with no ad spend. Written as plain rules for the Station agent.
 * It is deliberately blunt: nobody can be instantly first for a search, and the agent must never
 * promise that. What it can do is pick searches a new site can win and build pages that deserve to.
 */
export const SEARCH_PLAYBOOK = `Getting found by search, with no ad spend. Be honest about the limit first: no site can be put at the top of a search on day one. A new domain starts with no trust, search engines take days to weeks to index it and months to rank it, and anyone who promises instant first place is selling something. Your job is to choose searches a new site can realistically win, build pages that deserve to rank, and make everything the owner would otherwise have to do (submitting, measuring, updating) automatic. Never claim a ranking, a visitor count or earnings you have not measured.

1. Pick the search before you pick the product. Tools and utilities that people search for by name already have steady demand without any advertising: image resizer, image converter (png to jpg, heic to jpg, webp to png), compress image to 100kb, merge pdf, word counter, qr code generator, unit and date calculators, case converter, countdown timer. These searches are huge and crowded, so do not target the head term. Target the long tail a small site can win: a specific format pair, a specific size, a specific use ("resize image for passport photo", "compress png under 200kb", "convert heic to jpg without uploading"). Evidence first: use search autocomplete (the suggestions that appear as a phrase is typed, fetched with a bounded request) and related searches to list what people actually type, favour phrases with a clear single intent and many variants, and write the chosen phrases into STORE-LOG.md with how you found them. Reject a phrase when the first results are all giant brands with no small site in sight, or when the tool cannot be done fully in the browser.

2. One page per search intent. Each phrase gets its own page with its own address, for example /convert/heic-to-jpg and /resize/image-to-200kb. The working tool sits at the top of the page so the visitor is done in seconds, with no signup and no wall. Below it, write a short honest explainer in your own words: what it does, how the file is handled, limits, and two or three questions a person really has. Do not make hundreds of near-identical pages with swapped words. A search engine treats that as spam and will bury the whole site. Start with a small set of pages that are each genuinely useful, and add one only when the last one is finished and measured.

3. Make the tool better than the top result, in ways a visitor feels. It loads fast, works on a phone, handles several files at once, shows before and after sizes, and keeps files on the device (state this plainly, and make it true: processing in the browser, nothing uploaded). Speed and trust are ranking signals and conversion signals at once.

4. On-page basics, every page. One clear title tag with the phrase near the front, under about 60 characters, and a meta description that reads like a person wrote it. One h1 that matches the intent. A short readable address. Descriptive alt text on real images. Internal links between related tools in plain sentences ("need a smaller file? use the compressor"), a visible nav and footer that reach every page, and breadcrumbs. Structured data (JSON-LD) that is true for the page: WebApplication or SoftwareApplication for a tool, FAQPage for a real FAQ, BreadcrumbList. Never mark up reviews or ratings that do not exist.

5. Technical basics a new site must get right. Static, server-rendered HTML so the tool and its text are in the page source. A sitemap.xml that lists every page and a robots.txt that points to it. A canonical link on every page. Valid https. No broken links or redirect chains. Core web vitals: no layout shift, images sized, scripts deferred, the tool interactive fast on a mid phone. Run the real checks you can (a headless browser page load, a link crawl, Lighthouse if it installs) and fix what they flag. Record the numbers.

6. Get indexed without the owner doing anything. Use IndexNow, the free open protocol that tells participating search engines about new and changed addresses with one request and a key file hosted on the site. Add it to the deploy step. Also ship the sitemap and tell the owner once, in your report, that connecting the site to the free Google Search Console and Bing Webmaster Tools takes two minutes and is the only way to see real queries and clicks, since you cannot create those accounts for them. Do not pretend to have done it.

7. Earn links honestly, only where it is free and allowed. A new site has none, and links are most of what makes a page trusted. Legitimate free routes: a plainly useful "how this works" write-up that other people can cite, a listing in relevant free tool directories and open-source or maker showcase sites where self-submission is welcome, and a short launch post on communities that permit it, written once for the owner to post and never spammed. Do not buy links, trade links in bulk, post fake reviews, or generate fake accounts. Those get sites removed from search, and they are against the rules of every platform.

8. Make money without spoiling the tool. Plan the layout for a labelled ad slot or a sponsor slot that is beside the tool and never between the visitor and the result. Until real traffic exists, do not wire an ad network and do not show empty boxes: build a /advertise page that states honestly what the site is and that traffic is new. Ad networks and sponsors only pay when there are visitors, so say that plainly in the report, and give the owner the one account they would need to open later.

9. Measure, then change one thing. Keep a search log in STORE-LOG.md: the pages, the phrase each targets, the date it shipped, the date it was submitted, and any measured result. Use privacy-friendly free analytics only if it needs no account you do not have. On every maintenance pass, check the site still loads, the sitemap is current, and no page broke, then add or improve exactly one page based on what the log shows. Drop a page idea that gets nothing after a fair wait and write down why. Be patient: a ranking change takes weeks to show, so judge in weeks, not on the next pass.

10. State the timeline honestly in every report: first indexing in days to weeks, first small rankings in about one to three months, meaningful traffic not guaranteed, ad income small until thousands of visits a day.`
