/**
 * What a Station agent can choose to build, and how it should look. Kept as data so the brief,
 * the plan, and the tests all read the same list instead of drifting apart.
 *
 * Every model here has to run with no work from the owner and no fixed cost. "Time to first sale"
 * is deliberately blunt: most of these take months, and the agent must say so instead of promising
 * income.
 */

export interface BusinessModel {
  id: string
  name: string
  sells: string
  /** The free-to-run stack that makes it work. */
  stack: string
  /** Accounts the owner must create once; the agent cannot. */
  ownerSetup: string
  timeToFirstSale: string
  honestRisk: string
}

export const BUSINESS_MODELS: BusinessModel[] = [
  {
    id: 'printables',
    name: 'Digital printables shop',
    sells: 'Planners, trackers, worksheets, wall art, checklists as downloadable PDFs and images the agent draws itself.',
    stack: 'Static site on a free host, Stripe Checkout, a function that emails a time-limited download link.',
    ownerSetup: 'Free host token, Stripe.',
    timeToFirstSale: 'Weeks to months; depends on search traffic.',
    honestRisk: 'Crowded niche. Needs a narrow angle and pages that rank.',
  },
  {
    id: 'templates',
    name: 'Template and spreadsheet shop',
    sells: 'Budget sheets, invoice and resume templates, meal planners, trackers, document packs as files.',
    stack: 'Same as printables; files generated by script, delivered by link after payment.',
    ownerSetup: 'Free host token, Stripe.',
    timeToFirstSale: 'Weeks to months.',
    honestRisk: 'Buyers compare against free templates, so quality and a clear use case must be obvious.',
  },
  {
    id: 'guides',
    name: 'Paid guides and mini courses',
    sells: 'Short, practical, narrow PDF guides, checklists and email courses the agent researches and writes.',
    stack: 'Static site, Stripe Checkout, emailed link or an email drip through a free email tier.',
    ownerSetup: 'Free host token, Stripe, a free email service key.',
    timeToFirstSale: 'Months; trust has to be earned with free samples first.',
    honestRisk: 'Thin or generic content is punished by buyers and search engines. Needs real depth and sources.',
  },
  {
    id: 'utility',
    name: 'Free utility site paid by ads and sponsors',
    sells: 'A set of single-purpose tools people search for by name (image resizer, file converter, word counter, unit or date calculator, QR code maker, PDF merger). Free to use, paid by an ad slot or a flat monthly sponsor slot.',
    stack: 'Pure static pages on a free host. Every tool runs in the visitor browser (canvas, WebAssembly, File API), so there is no server, no upload and no running cost. One landing page per search phrase, each with the working tool above the fold and a short honest explainer below. An ad slot placeholder that is wired once the owner adds an ad network, plus a sponsor page.',
    ownerSetup: 'Free host token. Later, one ad network or sponsor payment link if traffic arrives.',
    timeToFirstSale: 'Months of search ranking before any visitors; ad income stays tiny until traffic is in the thousands a day.',
    honestRisk: 'Crowded searches. Pick narrow, specific phrases, make the tool load fast and work offline, and never claim traffic or earnings. Ads must stay clearly labelled and out of the way of the tool.',
  },
  {
    id: 'tools',
    name: 'Small paid web tools',
    sells: 'A useful calculator, generator or checker that is free to try and paid to unlock or export.',
    stack: 'Static front end plus serverless functions on a free host, Stripe for the paid tier.',
    ownerSetup: 'Free host token, Stripe.',
    timeToFirstSale: 'Months; tools earn by ranking for a specific search.',
    honestRisk: 'Must genuinely work and beat free alternatives. Best fit for a coding agent.',
  },
  {
    id: 'newsletter',
    name: 'Niche newsletter',
    sells: 'A free, regular, genuinely useful email on one narrow topic, with an optional paid tier; ads and sponsor slots become possible only after it has a real audience.',
    stack: 'Signup site on a free host, a free email tier for sending, an archive of past issues for search traffic, Stripe for a paid tier or sponsor invoices.',
    ownerSetup: 'Free host token, a free email service key. Ad and affiliate programs usually need the owner to apply and be approved.',
    timeToFirstSale: 'Many months. Sponsors and ad networks want a real audience, commonly thousands of subscribers.',
    honestRisk: 'No audience means no ad revenue. Build the audience engine first; verify that the chosen email service can actually send automatically on its available plan. Never promise ad offers or approvals.',
  },
  {
    id: 'affiliate',
    name: 'Niche review and guide site',
    sells: 'Honest, specific buying guides and comparisons in one niche that earn commission through affiliate links.',
    stack: 'Static site on a free host, pages written from real research, email capture.',
    ownerSetup: 'Free host token. Affiliate programs need the owner to apply and be approved; some approve instantly.',
    timeToFirstSale: 'Many months; search rankings are slow.',
    honestRisk: 'Mass produced, shallow pages get ignored or penalised by search engines. Fewer, better pages only.',
  },
  {
    id: 'directory',
    name: 'Curated directory',
    sells: 'A well organised, real, regularly updated list of a niche (tools, suppliers, venues) with paid featured listings.',
    stack: 'Static site with data files, Stripe for featured listings and a form for submissions.',
    ownerSetup: 'Free host token, Stripe.',
    timeToFirstSale: 'Months; needs visitors before anyone pays to be listed.',
    honestRisk: 'Only valuable if the data is accurate and kept current; stale listings destroy trust.',
  },
  {
    id: 'pod',
    name: 'Print-on-demand niche store',
    sells: 'Stickers, posters, mugs, totes in one tight niche, printed and shipped by Printful per order.',
    stack: 'Static site on a free host, Stripe Checkout, a webhook that creates the order through the Printful API.',
    ownerSetup: 'Free host token, Stripe, Printful with a card on file.',
    timeToFirstSale: 'Months; thin margins (a sticker clears a couple of dollars).',
    honestRisk: 'Crowded and low margin. Prices must cover Printful cost, shipping and Stripe fees.',
  },
  {
    id: 'reports',
    name: 'Niche data and report shop',
    sells: 'A repeatable, useful report or downloadable dataset assembled from primary sources the agent is allowed to reuse, with a sample buyers can inspect.',
    stack: 'Static sample and methodology pages on a free host, a scheduled data pipeline, Stripe Checkout, and automatic file delivery after payment.',
    ownerSetup: 'Free host token and Stripe; access to a licensed or openly reusable data source if public data is insufficient.',
    timeToFirstSale: 'Weeks to months if a specific buyer problem is validated; no sale is assured.',
    honestRisk: 'A scraped list or AI summary is not a sellable report. Verify source rights, freshness, accuracy, and a real buyer use case; stop updates if the source disappears.',
  },
  {
    id: 'alerts',
    name: 'Paid niche alerts',
    sells: 'Timely, filtered alerts from permitted public or licensed sources, such as new grants, calls for proposals, or relevant product changes.',
    stack: 'Scheduled source checks on a free host, deduplication and provenance logs, opt-in email delivery, and Stripe for paid access.',
    ownerSetup: 'Free host token, Stripe, and an email service key; source access must permit automated reuse.',
    timeToFirstSale: 'Months; buyers must see that alerts arrive accurately and early enough to be useful.',
    honestRisk: 'Missed or false alerts destroy trust. Do not sell a subscription until source access, delivery, unsubscribe, and repeated scheduled runs are verified.',
  },
  {
    id: 'leadgen',
    name: 'Niche lead-generation site',
    sells: 'A focused comparison or matching tool that collects consented enquiries and routes qualified leads to a verified service provider.',
    stack: 'Useful static pages and a qualification form on a free host, consent and routing records, spam filtering, and automated delivery to a contracted buyer.',
    ownerSetup: 'Free host token and a real buyer agreement with agreed lead criteria, price, and consent language before monetization.',
    timeToFirstSale: 'Months; the site needs targeted visitors and a buyer who accepts the leads.',
    honestRisk: 'An enquiry form is not income. Never collect or sell personal details without explicit consent and a verified recipient; do not claim a buyer or payout that is not contracted.',
  },
  {
    id: 'jobboard',
    name: 'Niche job board',
    sells: 'A small, accurate board for one profession or location, with self-serve paid employer postings after job-seeker traffic exists.',
    stack: 'Searchable listings on a free host, verified employer submission and expiry, Stripe Checkout for postings, and links to employer application pages.',
    ownerSetup: 'Free host token and Stripe; access to jobs the agent has permission to list or employers willing to submit them.',
    timeToFirstSale: 'Months; employers pay only if relevant job seekers use the board.',
    honestRisk: 'Empty or stale jobs make the board useless. Verify each listing, remove expired ones, avoid collecting resumes, and do not invent employer relationships.',
  },
]

export interface StoreTheme {
  id: string
  name: string
  mood: string
  palette: string
  type: string
  layout: string
  motion: string
  bestFor: string
}

export const STORE_THEMES: StoreTheme[] = [
  { id: 'paper-editorial', name: 'Paper editorial', mood: 'warm, literary, calm', palette: 'cream #fbf5ea, ink #2a2118, terracotta #c8553d, sage #7a8b69', type: 'a high-contrast serif for headings, a quiet sans for body', layout: 'wide margins, big headline, asymmetric image blocks', motion: 'slow fades, underline draws on hover', bestFor: 'reading, journaling, tea, stationery' },
  { id: 'swiss-grid', name: 'Swiss grid', mood: 'precise, modern, confident', palette: 'white #ffffff, black #111111, one signal colour such as #ff3b1f', type: 'a neo-grotesque sans, tight tracking, huge numerals', layout: 'strict 12 column grid, hairline rules, lots of white space', motion: 'crisp snaps, no easing flourishes', bestFor: 'tools, calculators, planners, finance' },
  { id: 'soft-pastel', name: 'Soft pastel playful', mood: 'friendly, light, kind', palette: 'blush #ffe3e8, mint #d9f2e6, butter #fff3c4, lilac #e6defa, ink #3b3347', type: 'a rounded sans with generous line height', layout: 'rounded cards, stickers and blobs, overlapping shapes', motion: 'gentle bounces, wobble on hover', bestFor: 'kids, self care, habit trackers, cute stationery' },
  { id: 'dark-luxe', name: 'Dark luxe', mood: 'premium, moody, exclusive', palette: 'near black #0e0d0c, warm grey #8a847b, gold #c9a45c, off white #f1ece2', type: 'an elegant serif display with a small caps sans', layout: 'full bleed imagery, centred hero, thin gold dividers', motion: 'slow parallax, fade up on scroll', bestFor: 'premium guides, wedding stationery, luxury templates' },
  { id: 'retro-70s', name: 'Retro seventies', mood: 'warm, nostalgic, groovy', palette: 'mustard #e0a526, burnt orange #d1561d, brown #4a2c1a, cream #f6e7c8, teal #2f7f7a', type: 'a chunky rounded serif with a rounded sans', layout: 'stripes, sunbursts, rounded corners, badges', motion: 'rolling marquees, springy hovers', bestFor: 'music, travel, home, vintage style products' },
  { id: 'botanical', name: 'Botanical studio', mood: 'fresh, natural, grounded', palette: 'leaf #3f6b4f, moss #a9bf8f, clay #c98f6b, linen #f4efe6', type: 'a humanist serif and a clean sans', layout: 'organic shapes, line drawn plants, airy sections', motion: 'leaves that drift, soft reveals', bestFor: 'plants, wellness, gardening, home' },
  { id: 'notebook', name: 'Hand drawn notebook', mood: 'personal, scrappy, human', palette: 'lined paper #fdfcf7, blue pen #2b4a9b, red margin #d9534f, highlighter #fff176', type: 'a handwriting display font with a plain readable body', layout: 'ruled backgrounds, tape corners, doodle arrows, tilted cards', motion: 'pen draw on, slight shake on hover', bestFor: 'students, planners, journaling, creative tools' },
  { id: 'brutalist', name: 'Brutalist mono', mood: 'raw, blunt, internet native', palette: 'white #ffffff, black #000000, hard colour blocks such as #ffe600 or #3a3aff', type: 'a monospace everywhere, oversized', layout: 'thick borders, hard shadows, visible structure, no rounding', motion: 'instant jumps, glitchy hover', bestFor: 'developer tools, zines, edgy templates, newsletters' },
  { id: 'nordic', name: 'Nordic minimal', mood: 'quiet, airy, honest', palette: 'snow #f7f8f9, stone #d8dcdf, slate #3d4650, one muted accent #6f9bb1', type: 'a light geometric sans', layout: 'very generous spacing, small precise type, single column rhythm', motion: 'barely there fades', bestFor: 'productivity, budgeting, minimalist planners' },
  { id: 'y2k', name: 'Y2K gloss', mood: 'bubbly, digital, glossy', palette: 'chrome #c9d1dc, hot pink #ff4fb0, cyber blue #3ec9ff, lime #b6ff3b', type: 'a rounded techno sans, outlined headlines', layout: 'glossy buttons, stars, sticker shapes, gradients used with taste', motion: 'shimmer, floating elements', bestFor: 'stickers, wallpapers, social media template packs' },
  { id: 'field-guide', name: 'Field guide', mood: 'practical, trusted, outdoorsy', palette: 'olive #5c6b3a, khaki #cdbf94, rust #a5532b, parchment #f2ead7', type: 'a sturdy slab serif with a condensed sans for labels', layout: 'labelled diagrams, numbered sections, ruled tables', motion: 'minimal, tab and accordion transitions', bestFor: 'guides, checklists, how-to content, travel' },
  { id: 'newsprint', name: 'Newsprint', mood: 'editorial, serious, readable', palette: 'newsprint #f1eee6, black #151515, red rule #c1272d', type: 'a classic news serif with a condensed sans', layout: 'columns, bylines, big pull quotes, dense but ordered', motion: 'subtle, sticky section headers', bestFor: 'newsletters, review sites, directories, reports' },
]

/** Compact text for the brief. Short on purpose: the agent should choose, not read an essay. */
export function describeBusinessModels(): string {
  return BUSINESS_MODELS.map((m, i) => `${i + 1}. ${m.name}: ${m.sells} Stack: ${m.stack} Owner sets up once: ${m.ownerSetup} First sale: ${m.timeToFirstSale} Risk: ${m.honestRisk}`).join(' ')
}

export function describeThemes(): string {
  return STORE_THEMES.map((t) => `${t.name} (${t.mood}; palette ${t.palette}; type: ${t.type}; layout: ${t.layout}; motion: ${t.motion}; suits ${t.bestFor})`).join(' | ')
}
